updated github workflow

diff --git a/.github/workflows/poetry.yml b/.github/workflows/poetry.yml
--- a/.github/workflows/poetry.yml
+++ b/.github/workflows/poetry.yml
@@ -56,7 +56,10 @@ jobs:
           source $VENV
           ruff src/clev2er
           # check that all src directories contain a __init__.py
-          find src -type d \( -name '.*' -o -name '__*' \) -prune -o -type d ! -exec test -e '{}/__init__.py' \; -print
+          if find src -type d \( -name '.*' -o -name '__*' \) -prune -o -type d ! -exec test -e '{}/__init__.py' \; -print | grep -q .; then
+            echo "Missing __init__.py in some directories."
+            exit 1
+          fi
           pylint --version
           pylint src/clev2er
           #pylint src/clev2er/algorithms/testchain/alg_template1.py
